services:
  postgres:
    command: ["postgres", "-c", "log_statement=all"]
    container_name: postgres
    env_file: ./docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_URL"]
      interval: 10s
      timeout: 5s
      retries: 10
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  postgres.migrate:
    command: ["up"]
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["migrate", "-database", "$POSTGRES_URL", "-path", "/migrations"]
    env_file: ./docker.env
    image: migrate/migrate
    volumes:
      - ../migrations:/migrations

  pgadmin:
    configs:
      - source: pgpass
        target: /pgpass
      - source: servers.json
        target: /pgadmin4/servers.json
    container_name: pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ./docker.env
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - ./pg_admin:/var/lib/pgadmin

  server:
    build: ..
    container_name: server
    depends_on:
      postgres:
        condition: service_healthy
      postgres.migrate:
        condition: service_completed_successfully
    env_file: ../.env
    ports:
      - "3000:3000"

configs:
  pgpass:
    file: ./pg_config/pgpass
  servers.json:
    file: ./pg_config/servers.json
